### ISSUE TITLE
Roles-based auth isn't working :( - 403 error

### ISSUE THREAD

**Issue by ev1illyn** [ev1illyn/forum-spring-rest-api#3]
![image](https://user-images.githubusercontent.com/30708285/102547168-8b863580-4097-11eb-9e9b-b7b967fc67d0.png)

**Comment by xDrumstick** [comment]
Perfil.java

public String getAuthority() {
	return this.nome;
}

**Comment by ev1illyn** [comment]
@xDrumstick hey dude, it worked.
and I add/removed some other things to make it work too.
It was really nice of you. thank you!!
Feel free to make a pull request with these changes so you'll be contribuing to this project.
